# © 2026 Solvos Consultoría Informática (<http://www.solvos.es>)
# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html

import base64
import io
import logging

import qrcode

from odoo import _, api, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class DecaDocumentMixin(models.AbstractModel):
    """Generic mixin for generating DeCA documents (signed PDF + public URL
    + QR code) for any model that requires them.

    Models inheriting from this mixin must:
        - Define the fields `deca_enabled`, `deca_base_url`, and
            `deca_report_id` on their company (or wherever appropriate), or
            override `_get_deca_company` / `_get_deca_report` /
            `_get_deca_base_url` if the configuration is not company-based.
        - Override `_get_deca_url_path()` to specify the model-specific URL
            segment (for example, "l10n_es_stock_picking_deca/deca").
        - Override `_check_deca_can_generate_extra()` to add model-specific
            checks (states, signature, operation type, etc.).
        - Optionally override `_get_deca_document_name()` to customize the
            name of the attached PDF.
    """
    _name = 'deca.document.mixin'
    _description = "DeCA Document Mixin"

    deca_is_generated = fields.Boolean(
        string="DeCA document generated",
        copy=False,
        help="Indicates that this record has a DeCA document generated.",
    )
    deca_url = fields.Char(
        string="DeCA URL",
        compute="_compute_deca_data",
    )
    deca_qr = fields.Binary(
        string="DeCA QR code",
        compute="_compute_deca_data",
    )
    deca_attachment_id = fields.Many2one(
        'ir.attachment',
        string="DeCA PDF",
        copy=False,
    )
    deca_generation_date = fields.Datetime(
        string="DeCA generation date",
        copy=False,
    )
    deca_generated_by_id = fields.Many2one(
        'res.users',
        string="Generated by",
        copy=False,
    )

    deca_company_enabled = fields.Boolean(
        compute="_compute_deca_company_enabled",
        string="DeCA enabled on company",
    )


    def _get_deca_company(self):
        self.ensure_one()
        return self.company_id

    def _get_deca_enabled(self):
        self.ensure_one()
        return bool(self._get_deca_company().deca_enabled)

    def _get_deca_base_url(self):
        self.ensure_one()
        return self._get_deca_company().deca_base_url

    def _get_deca_report(self):
        self.ensure_one()
        return self._get_deca_company().deca_report_id

    def _get_deca_url_path(self):
        """Model-specific URL segment, for example:
        'l10n_es_stock_picking_deca/deca'. Must be overridden."""
        self.ensure_one()
        raise NotImplementedError(
            "Models inheriting from deca.document.mixin must "
            "implement _get_deca_url_path()."
        )

    def _get_deca_document_name(self):
        self.ensure_one()
        name = getattr(self, 'name', False) or self.id
        return "DeCA_%s.pdf" % name

    def _check_deca_can_generate_extra(self):
        """Model-specific check points (state, signature, type, etc.). Does nothing by default."""
        self.ensure_one()

    # ------------------------------------------------------------
    # Generic logic
    # ------------------------------------------------------------
    # NOTE: `api.depends` does not support lambdas/callables in Odoo, it needs
    # literal field names. It is assumed that the model inheriting the
    # mixin has a `company_id` field (like stock.picking). If any
    # inheriting model did not have it, or its `_get_deca_company` does not
    # dependiera de `company_id`, deberá sobrescribir estos dos métodos
    # `_compute_deca_data` y `_compute_deca_company_enabled` añadiendo el
    # `@api.depends` adecuado.
    @api.depends("company_id.deca_enabled", "company_id.deca_base_url")
    def _compute_deca_data(self):
        deca_enabled_records = self.filtered(lambda x: x._get_deca_enabled())
        for record in deca_enabled_records:
            deca_url = "%s/%s/%s" % (
                record._get_deca_base_url().rstrip('/'),
                record._get_deca_url_path(),
                record.id,
            )
            record.update({
                "deca_url": deca_url,
                "deca_qr": record._get_deca_qr_code(deca_url),
            })
        (self - deca_enabled_records).update({
            "deca_url": False,
            "deca_qr": False,
        })

    @api.depends("company_id.deca_enabled")
    def _compute_deca_company_enabled(self):
        for record in self:
            record.deca_company_enabled = record._get_deca_enabled()

    def action_generate_deca(self):
        self.ensure_one()
        self._check_deca_can_generate()
        self._generate_deca_document()
        return True

    def _check_deca_can_generate(self):
        self.ensure_one()
        company = self._get_deca_company()
        if not self._get_deca_enabled():
            raise UserError(_(
                "The DeCA functionality is not enabled for company %s."
            ) % company.display_name)
        if not self._get_deca_report():
            raise UserError(_(
                "No report is configured as the DeCA document in the "
                "settings of company %s."
            ) % company.display_name)
        if not self._get_deca_base_url():
            raise UserError(_(
                "No base URL is configured for DeCA in the settings of "
                "company %s."
            ) % company.display_name)
        self._check_deca_can_generate_extra()

    def _generate_deca_document(self):
        """Generates (or regenerates) the DeCA PDF, attaches it to the record,
        and computes its public URL. Replaces the previous attachment, if any."""
        self.ensure_one()
        report = self._get_deca_report()

        is_regeneration = bool(self.deca_is_generated)
        old_attachment = self.deca_attachment_id

        self.write({
            'deca_is_generated': True,
            'deca_generation_date': fields.Datetime.now(),
            'deca_generated_by_id': self.env.user.id,
        })

        pdf_content, _report_type = self.env['ir.actions.report'].sudo()._render_qweb_pdf(
            report.id, self.ids
        )

        attachment = self.env['ir.attachment'].sudo().create({
            'name': self._get_deca_document_name(),
            'type': 'binary',
            'datas': base64.b64encode(pdf_content),
            'res_model': self._name,
            'res_id': self.id,
            'mimetype': 'application/pdf',
        })

        self.deca_attachment_id = attachment
        if old_attachment:
            old_attachment.sudo().unlink()

        message = (
            _(
                "DeCA document regenerated by %(user)s. New URL: %(url)s"
            ) if is_regeneration
            else _(
                "DeCA document generated by %(user)s. URL: %(url)s"
            )
        )
        self.message_post(body=(message % {'user': self.env.user.name, 'url': self.deca_url}))

        _logger.info("DeCA %s for %s record %s (%s)",
                    "regenerated" if is_regeneration else "generated",
                    self._name, self.display_name, self.deca_url)

    def _get_deca_qr_code(self, url):
        if not url:
            return False
        qr = qrcode.QRCode(box_size=4, border=1)
        qr.add_data(url)
        qr.make(fit=True)
        qr_image = qr.make_image()
        with io.BytesIO() as temp:
            qr_image.save(temp, format="PNG")
            deca_qr_code = base64.b64encode(temp.getvalue())
        return deca_qr_code
