# © 2026 Solvos Consultoría Informática (<http://www.solvos.es>)
# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html

import base64
import io
import logging

import qrcode

from odoo import _, api, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class StockPicking(models.Model):
    _inherit = 'stock.picking'

    deca_is_generated = fields.Boolean(
        string="DeCA document generated",
        copy=False,
        help="Indicates that this delivery order has a DeCA document generated.",
    )
    deca_url = fields.Char(
        string="DeCA URL",
        compute="_compute_deca_data",
    )
    deca_qr = fields.Binary(
        string="DeCA QR code",
        compute="_compute_deca_data",
    )
    deca_attachment_id = fields.Many2one(
        'ir.attachment',
        string="DeCA PDF",
        copy=False,
    )
    deca_generation_date = fields.Datetime(
        string="DeCA generation date",
        copy=False,
    )
    deca_generated_by_id = fields.Many2one(
        'res.users',
        string="Generated by",
        copy=False,
    )

    deca_company_enabled = fields.Boolean(
        related='company_id.deca_enabled',
        string="DeCA enabled on company",
    )

    @api.depends("company_id.deca_enabled", "company_id.deca_base_url")
    def _compute_deca_data(self):
        pick_deca = self.filtered(lambda x: x.company_id.deca_enabled)
        for record in pick_deca:
            deca_url = "%s/l10n_es_stock_picking_deca/deca/%s" % (
                record.company_id.deca_base_url.rstrip('/'), record.id
            )
            record.update({
                "deca_url": deca_url,
                "deca_qr": record._get_deca_qr_code(deca_url),
            })
        (self - pick_deca).update({            
            "deca_url": False,
            "deca_qr": False,
        })

    def action_generate_deca(self):
        self.ensure_one()
        self._check_deca_can_generate()
        self._generate_deca_document()
        return True

    def _check_deca_can_generate(self):
        self.ensure_one()
        if not self.company_id.deca_enabled:
            raise UserError(_(
                "The DeCA functionality is not enabled for company %s."
            ) % self.company_id.display_name)
        if self.picking_type_code != 'outgoing':
            raise UserError(_(
                "The DeCA document can only be generated for outgoing delivery orders."
            ))
        if self.state != 'done':
            raise UserError(_(
                "The delivery order must be in the 'Done' state to generate the DeCA document."
            ))
        if not self.signature:
            raise UserError(_(
                "The delivery order must be signed before generating the DeCA "
                "document. Please sign the delivery order first."
            ))
        if not self.company_id.deca_report_id:
            raise UserError(_(
                "No report is configured as the DeCA document in the "
                "settings of company %s."
            ) % self.company_id.display_name)
        if not self.company_id.deca_base_url:
            raise UserError(_(
                "No base URL is configured for DeCA in the settings of "
                "company %s."
            ) % self.company_id.display_name)

    def _generate_deca_document(self):
        """Generate (or regenerate) the DeCA PDF, attach it to the picking
        and compute its public URL. Replaces the previous attachment, if
        any."""
        self.ensure_one()
        company = self.company_id
        report = company.deca_report_id

        is_regeneration = bool(self.deca_is_generated)
        old_attachment = self.deca_attachment_id

        self.write({
            'deca_is_generated': True,
            'deca_generation_date': fields.Datetime.now(),
            'deca_generated_by_id': self.env.user.id,
        })

        pdf_content, _report_type = self.env['ir.actions.report'].sudo()._render_qweb_pdf(
            report.id, self.ids
        )

        attachment = self.env['ir.attachment'].sudo().create({
            'name': "DeCA_%s.pdf" % (self.name or self.id),
            'type': 'binary',
            'datas': base64.b64encode(pdf_content),
            'res_model': self._name,
            'res_id': self.id,
            'mimetype': 'application/pdf',
        })

        self.deca_attachment_id = attachment

        # The previous attachment is no longer referenced by the picking,
        # so it can now be deleted without triggering the deletion guard on
        # ir.attachment.
        if old_attachment:
            old_attachment.sudo().unlink()

        message = (
            _(
                "DeCA document regenerated by %(user)s. New URL: %(url)s"
            ) if is_regeneration
            else _(
                "DeCA document generated by %(user)s. URL: %(url)s"
            )
        )
        self.message_post(body=(message % {'user': self.env.user.name, 'url': self.deca_url}))

        _logger.info("DeCA %s for picking %s (%s)",
                     "regenerated" if is_regeneration else "generated",
                     self.name, self.deca_url)

    def _get_deca_qr_code(self, url):
        if not url:
            return False
        qr = qrcode.QRCode(box_size=4, border=1)
        qr.add_data(url)
        qr.make(fit=True)
        qr_image = qr.make_image()
        with io.BytesIO() as temp:
            qr_image.save(temp, format="PNG")
            deca_qr_code = base64.b64encode(temp.getvalue())    
        return deca_qr_code
