# -*- coding: utf-8 -*-
import base64
import io
import logging

import qrcode

from odoo import _, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class StockPicking(models.Model):
    _inherit = 'stock.picking'

    deca_is_generated = fields.Boolean(
        string="DeCA document generated",
        copy=False,
        help="Indicates that this delivery order has a DeCA document generated.",
    )
    # URL-type field (rendered with the 'url' widget on a Char; the Odoo ORM
    # has no native "Url" field type).
    deca_url = fields.Char(
        string="DeCA URL",
        copy=False,
    )
    deca_attachment_id = fields.Many2one(
        'ir.attachment',
        string="DeCA PDF",
        copy=False,
    )
    deca_generation_date = fields.Datetime(
        string="DeCA generation date",
        copy=False,
    )
    deca_generated_by_id = fields.Many2one(
        'res.users',
        string="Generated by",
        copy=False,
    )

    # Technical helper field used to condition the view without exposing
    # company_id.deca_enabled directly in attrs expressions.
    deca_company_enabled = fields.Boolean(
        related='company_id.deca_enabled',
        string="DeCA enabled on company",
    )

    def action_generate_deca(self):
        """'Generate DeCA document' button.

        If the document was already generated, open a confirmation wizard
        before regenerating it. Otherwise, generate it directly.
        """
        self.ensure_one()
        self._check_deca_can_generate()

        if self.deca_is_generated:
            return {
                'type': 'ir.actions.act_window',
                'name': _("Regenerate DeCA document"),
                'res_model': 'stock.picking.deca.confirm.wizard',
                'view_mode': 'form',
                'target': 'new',
                'context': {'default_picking_id': self.id},
            }

        self._generate_deca_document()
        return True

    def _check_deca_can_generate(self):
        self.ensure_one()
        if not self.company_id.deca_enabled:
            raise UserError(_(
                "The DeCA functionality is not enabled for company %s."
            ) % self.company_id.display_name)
        if self.picking_type_code != 'outgoing':
            raise UserError(_(
                "The DeCA document can only be generated for outgoing delivery orders."
            ))
        if self.state != 'done':
            raise UserError(_(
                "The delivery order must be in the 'Done' state to generate the DeCA document."
            ))
        if not self.signature:
            raise UserError(_(
                "The delivery order must be signed before generating the DeCA "
                "document. Please sign the delivery order first."
            ))

    def _generate_deca_document(self):
        """Generate (or regenerate) the DeCA PDF, attach it to the picking
        and compute its public URL. Replaces the previous attachment, if
        any."""
        self.ensure_one()
        company = self.company_id
        report = company.deca_report_id

        if not report:
            raise UserError(_(
                "No report is configured as the DeCA document in the "
                "settings of company %s."
            ) % company.display_name)
        if not company.deca_base_url:
            raise UserError(_(
                "No base URL is configured for DeCA in the settings of "
                "company %s."
            ) % company.display_name)

        is_regeneration = bool(self.deca_is_generated)
        old_attachment = self.deca_attachment_id

        pdf_content, _report_type = self.env['ir.actions.report'].sudo()._render_qweb_pdf(
            report.id, self.ids
        )

        attachment = self.env['ir.attachment'].sudo().create({
            'name': "DeCA_%s.pdf" % (self.name or self.id),
            'type': 'binary',
            'datas': base64.b64encode(pdf_content),
            'res_model': self._name,
            'res_id': self.id,
            'mimetype': 'application/pdf',
        })

        deca_url = "%s/l10n_es_stock_picking_deca/deca/%s" % (
            company.deca_base_url.rstrip('/'), self.id
        )

        self.write({
            'deca_is_generated': True,
            'deca_attachment_id': attachment.id,
            'deca_url': deca_url,
            'deca_generation_date': fields.Datetime.now(),
            'deca_generated_by_id': self.env.user.id,
        })

        # The previous attachment is no longer referenced by the picking,
        # so it can now be deleted without triggering the deletion guard on
        # ir.attachment.
        if old_attachment:
            old_attachment.sudo().unlink()

        if is_regeneration:
            self.message_post(body=_(
                "DeCA document regenerated by %(user)s. New URL: %(url)s"
            ) % {'user': self.env.user.name, 'url': deca_url})
        else:
            self.message_post(body=_(
                "DeCA document generated by %(user)s. URL: %(url)s"
            ) % {'user': self.env.user.name, 'url': deca_url})

        _logger.info("DeCA %s for picking %s (%s)",
                     "regenerated" if is_regeneration else "generated",
                     self.name, deca_url)

    def _get_deca_qr_code(self):
        """Return a base64-encoded PNG QR code pointing to the DeCA public
        URL of this picking, for use in the DeCA report (see
        https://github.com/OCA/l10n-spain/blob/17.0/l10n_es_verifactu_oca/models/verifactu_mixin.py
        for a similar approach based on the 'qrcode' python library)."""
        self.ensure_one()
        if not self.deca_url:
            return False
        qr = qrcode.QRCode(box_size=4, border=1)
        qr.add_data(self.deca_url)
        qr.make(fit=True)
        qr_image = qr.make_image()
        stream = io.BytesIO()
        qr_image.save(stream, format="PNG")
        return base64.b64encode(stream.getvalue())
